---
all:
  hosts:
    WEB-A:
      ansible_connection: local
      forgeflow_container: forgeflow-web-a
      forgeflow_role: web
    WEB-B:
      ansible_connection: local
      forgeflow_container: forgeflow-web-b
      forgeflow_role: web
    DB-A:
      ansible_connection: local
      forgeflow_container: forgeflow-db-a
      forgeflow_role: database
    DB-B:
      ansible_connection: local
      forgeflow_container: forgeflow-db-b
      forgeflow_role: database
    REDIS:
      ansible_connection: local
      forgeflow_container: forgeflow-redis
      forgeflow_role: redis
  children:
    web:
      hosts:
        WEB-A:
        WEB-B:
    database:
      hosts:
        DB-A:
        DB-B:
    redis:
      hosts:
        REDIS:
