FROM httpd:2.4-bookworm

LABEL org.opencontainers.image.title="ForgeFlow Apache"
LABEL org.opencontainers.image.description="Apache frontend for ForgeFlow PHP-FPM"
LABEL org.opencontainers.image.source="https://github.com/guilzriel/forgeflow"

RUN sed -ri \
      -e 's/^#(LoadModule proxy_module modules\/mod_proxy\.so)/\1/' \
      -e 's/^#(LoadModule proxy_fcgi_module modules\/mod_proxy_fcgi\.so)/\1/' \
      -e 's/^#(LoadModule rewrite_module modules\/mod_rewrite\.so)/\1/' \
      -e 's/^#(LoadModule headers_module modules\/mod_headers\.so)/\1/' \
      /usr/local/apache2/conf/httpd.conf \
    && printf '\nServerName localhost\nInclude conf/extra/forgeflow.conf\n' \
      >> /usr/local/apache2/conf/httpd.conf

COPY docker/apache/forgeflow.conf \
  /usr/local/apache2/conf/extra/forgeflow.conf

COPY public /var/www/forgeflow/public

EXPOSE 8080

HEALTHCHECK --interval=10s --timeout=3s --retries=5 \
  CMD httpd -t || exit 1
